### ISSUE TITLE
Select webmap widget not working with 3.13 API  

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#100]
![selectwebmapwidget](https://cloud.githubusercontent.com/assets/5261405/6171603/ae76ca70-b301-11e4-9cf0-96a989d58b81.PNG)

**Comment by driskull** [comment]
@CTDisasterManagement can you provide a link to where this is occurring so I can test/send it to development?

**Comment by CTDisasterManagement** [comment]
Here is the link:
http://203.199.47.152/LimNextGen/ism_testing/?appid=750a3d38e8574f8bb7ebacfa986263ed&edit=t

Username/Password: bisen123

**Comment by driskull** [comment]
@CTDisasterManagement looks like once I click the pagination arrow to the left it starts working. Like the page number is not being set correctly or its not starting up.

Also, I see this error:
```
TypeError: Cannot read property 'geometry' of undefined {stack: (...), message: "Cannot read property 'geometry' of undefined"} "TypeError: Cannot read property 'geometry' of undefined
    at Object.g.graphicsExtent (http://jsdev.arcgis.com/3.13/init.js:1292:108)
    at declare._zoomToFeature (http://203.199.47.152/LimNextGen/ism_testing/js/AreaOfInterest.js:666:57)
    at null.<anonymous> (http://203.199.47.152/LimNextGen/ism_testing/js/AreaOfInterest.js:429:30)
    at g.hitch (http://jsdev.arcgis.com/3.13/init.js:177:296)
    at a._resolve (http://jsdev.arcgis.com/3.13/init.js:1723:9)
    at a._query.n (http://jsdev.arcgis.com/3.13/init.js:1724:61)
    at http://jsdev.arcgis.com/3.13/init.js:1726:113
    at c (http://jsdev.arcgis.com/3.13/init.js:76:221)
    at d (http://jsdev.arcgis.com/3.13/init.js:76:10)
    at b.Deferred.resolve.callback (http://jsdev.arcgis.com/3.13/init.js:77:350)"
```

**Comment by driskull** [comment]
@CTDisasterManagement might not want to put password in here since it's public.

**Comment by driskull** [comment]
@CTDisasterManagement I posted the latest code from the AGOL viewer for this on Basecamp. Can you take a look and see what might be different or causing the issue?

Thanks

**Comment by CTDisasterManagement** [comment]
@driskull 

We compare the given code and in Grid.js(line number 126) "this.grid.startup();" statement was missing hence we added the above statement and it is working fine with 3.13 API.

Thanks!

**Comment by driskull** [comment]
Awesome!!! thanks @CTDisasterManagement
